### ISSUE TITLE
Remove obsolete packages from Maven Central

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#100]
The ones that've been renamed b/w 0.2.0 and 0.3.0, like `sbt-dump-event-schema_2.12_1.0` etc.

**Comment by MarconZet** [comment]
This can't be done using normal means, and shouldn't be. [StackOverflow](https://stackoverflow.com/questions/9789611/removing-an-artifact-from-maven-central)
