### ISSUE TITLE
Provide a non-Java-serialization-based Borer codec for OffsetDateTime

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#12]
There doesn't seem to be anything (?) like that in borer-core library at least... I'm getting `Could not find implicit Encoder[java.time.OffsetDateTime] for parameter receivedAtUtc of case class ...`

Maybe there is already another library (Borer-official or otherwise) that provides such codecs OOTB? Pls investigate

**Comment by MarconZet** [comment]
I tried searching for a library that satisfies this condition, but couldn't find any. The Borer-official libraries include codecs for Akka and Cats, but not `Serializable`. 

I have already implemented Codec for `java.time.OffsetDateTime`. Looking at my implementation, it may be possible to automatically create Codecs for all subtypes of `Serializable`, but that's putting a lot of faith in this mechanism.

**Comment by PawelLipski** [comment]
> The Borer-official libraries include codecs for Akka and Cats, but not Serializable.

Yes, that's expected, `Serializable` is a marker trait for Java serialization, which is a mechanism very different from what Borer offers :)

>  it may be possible to automatically create Codecs for all subtypes of Serializable

Again, we almost surely don't want that, as is goes against the philosophy of Borer ☹️

**Comment by PawelLipski** [comment]
Actually... how about https://github.com/plokhotnyuk/jsoniter-scala? Does it have some ready Borer codecs for `java.time` stuff like `OffsetDateTime`?

**Comment by MarconZet** [comment]
It has a lot of Borer codecs, and some `java.time` stuff is defined [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/b1ee52640fc34abf71889d5f32bc9f9702cbe316/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/BorerJsonEncodersDecoders.scala#L51)
Most of these are custom classes, but `java.time.*`, `BigDecimal` and `BigInt` may be useful.

**Comment by PawelLipski** [comment]
Ok so if you could replace the existing `org.virtuslab.akkasaferserializer.StandardCodecs#offsetDateTimeCodec` with some ready jsoniter stuff; pls leave it in PR #3 as is, open a separate PR for that

**Comment by PawelLipski** [comment]
Let's resolve the jsoniter vs borer discussion first though: https://github.com/VirtusLab/akka-safer-serializer/issues/7#issuecomment-827506055

**Comment by PawelLipski** [comment]
Removing the `high-priority` label since this is currently worked around by a Codec that delegates the work to Java serialization.

This is not a production-ready implementation though, so this issue still remains opened.

**Comment by PawelLipski** [comment]
Actually @sirthias ... can you think of any ready implementation?

**Comment by sirthias** [comment]
Writing a codec for `java.time.OffsetDateTime` is not hard at all.
It's just a question of how you want to represent it.

AFAICS an `OffsetDateTime` instance consists of basically two parts: a `LocalDateTime` and a `ZoneOffset`.
So, ideally we'd write codecs for those and then simply compose the codec for `OffsetDateTime` from them.

It looks like a `LocalDateTime` can simply be represented as a `Long` and a `ZoneOffset` can be mapped to an `Int`.
So, quite simple, if I see things correctly.

**Comment by PawelLipski** [comment]
Let's wait for #27 to clarify first

**Comment by plokhotnyuk** [comment]
Small and more efficient implementations of `.parse` and `.toString` for `java.time._` types are [here](https://github.com/zio/zio-json/tree/develop/zio-json/shared/src/main/scala/zio/json/javatime).

**Comment by PawelLipski** [comment]
Hmm @plokhotnyuk  is the code you linked zio-json-specific in any way? can it be easily adapted for the use with e.g. Borer? 🤔

**Comment by plokhotnyuk** [comment]
@PawelLipski No dependencies on zio or zio-json in the production code. Tests of that repo can be easy migrated from zio-test to scalatest or as an option you can chose to adopt [these scalatest tests](https://github.com/plokhotnyuk/jsoniter-scala/blob/a0fa7a5707c0a396a1167e7f598f8a4cb50daf54/jsoniter-scala-core/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReaderSpec.scala#L1149-L1258) due better coverage of negative cases.
