### ISSUE TITLE
Laguna: 3 dump files with the same contents, is it intended?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#130]
After running `sbt ashDumpPersistenceSchema`:

```
$ find . | grep 'target.*yaml'
./laguna-api/automation/target/automation-dump-persistence-schema-0.1.0-SNAPSHOT.yaml
./laguna-api/sidecar/target/sidecar-dump-persistence-schema-0.1.0-SNAPSHOT.yaml
./laguna-api/target/api-dump-persistence-schema-0.1.0-SNAPSHOT.yaml
```

All these 3 files are identical... despite `sidecar` and `automation` **not** depending on each other (`api` depends on both, though) . Is it expected? 🤔

**Comment by MarconZet** [comment]
What command is used for generating files?

**Comment by PawelLipski** [comment]
Just `sbt ashDumpPersistenceSchema`!

**Comment by MarconZet** [comment]
This behaviour is intended.

`ashDumpPersistenceSchema` resolves to `root / ashDumpPersistenceSchema`. `root` is an aggregate project, meaning it calls this task on all sub-projects that have it. This is why three files are generated.

**Comment by PawelLipski** [comment]
Right, the fact that the file has been generated in **all three modules** (all that enable ASH plugin) is intended... I'm more concerned about the **identical contents** part... shouldn't the dump in module X contain just classes reachable from X's classpath?

**Comment by MarconZet** [comment]
What goes into a dump is determined by what is found in `ashCompilerPluginCacheDirectory` directory. Because the directory is identical, the contents of dump are too.

Limiting dump to classes available from specified subproject never seemed to be important. Implementing this feature is possible, but time consuming.

**Comment by PawelLipski** [comment]
Okay, we've probably discussed that but I've forgotten 😅 I'll clarify that in README.md on my PR then
