### ISSUE TITLE
Optimize loading time of `CirceAkkaSerializer`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#138]
As noticed on Hydra (the commercial project), disabling `HydraCirceAkkaSerializer` (by commenting out the `serializers` and `serialization-bindings` piece of config) significantly decreases the loading time for `ActorTestKit`.

Some ideas for what could be sped up (subject to the exact measurements first, ofc):
1. Does `CirceTraitCodec` need `checkSerializableTypesForMissingCodec` call, esp. given that this should be enforced by codec-registration-checker in compile time? Is there any known scenario where the code (assuming CRC is enabled) compiles but `checkSerializableTypesForMissingCodec` throws an error?
2. Maybe `parentsUpToRegisteredTypeMap` takes a long time? but hard to get rid of that completely, what could be done is to lazify evaluation of individual map entries (so make `parentsUpToRegisteredTypeMap` a mutable, concurrent `Map` with keys computed on demand)

**Comment by LukaszKontowski** [comment]
In my opinion such checks like `checkSerializableTypesForMissingCodec` should not be part of initialization - all such things should be checked on compilation
