### ISSUE TITLE
False-positive `No codecs for ... registered` error when switching branches (sth wrong with incremental compilation?)

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#141]
Waiting for further details from the team. Just the combination of git commit + contents of `target/codec-registration-checker-cache.csv` should be enough.

**Comment by MarconZet** [comment]
Minimal repro:

1. From existing project with serialization create new branch
2. Add in the newly created branch new top level serializable class and register it in serializer
3. Compile the code
4. Checkout base branch
5. Compile the code ⚡ ⚡

**Comment by PawelLipski** [comment]
Also! @miloradvojnovic you can try reproducing this one locally, maybe the fix could be quick here (?)

**Comment by miloradvojnovic** [comment]
> Also! @miloradvojnovic you can try reproducing this one locally, maybe the fix could be quick here (?)

I can try it.

**Comment by LukaszKontowski** [comment]
The same false-positive compilation error is thrown without changing git branches - example repro steps:

1. On existing project add new top level serializable class and register it in serializer
2. Compile the code (compilation successful)
3. Delete this recently added top level serializable from source code and remove it's registration from serializer (just `git restore` on files affected by changes from step 1. )
4. Compile the code (compilation fails with the same error)
...
Work in progress 🧑‍🏭
