### ISSUE TITLE
Provide Appendix B in README: what happens for a non-serializable class under each combination of circumstances

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#163]
A table for cartesian product of:
* Akka 2.5, 2.6
* `akka.actor.allow-java-serialization` = `yes`, `no`
* (any other relevant dimension? although not sure what that could be; e.g. Scala version is unlikely to affect anything here)

Pls provide a detailed message from the exception/logs/warnings (not just a short description) for each case

To be referenced from the blog

**Comment by LukaszKontowski** [comment]
previous similar issue: https://github.com/VirtusLab/akka-serialization-helper/issues/113
