### ISSUE TITLE
Switch from using `Resolver.sonatypeRepo` to `sonatypeOssRepos` in .sbt files

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/akka-serialization-helper#202]
- This has to be done after updating sbt to 1.7.x version
- Since sbt 1.7.0 `Resolver.sonatypeRepo` is deprecated. We should use `sonatypeOssRepos` instead

**Comment by aluscent** [comment]
@LukaszKontowski I think I can fix this. I have faced this warning.

**Comment by PawelLipski** [comment]
Okay! pls proceed
