### ISSUE TITLE
Create end-to-end example of a working app under `examples/`

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/akka-serialization-helper#206]
Such app should:
- Use Circe Akka Serializer
- Use `@Serializer` and `@SerializabilityTrait` annotations properly
- Perform some basic akka serialization / deserialization
- Be available for compilation with all ASH compiler plugins
- Be mentioned in README.md and docs/GUIDE.md (work in progress) as a working example of ASH usage

As for this issue - it should be as simple as possible - so that users will understand it in a flash.

**Comment by PawelLipski** [comment]
Also: remember to add path for the example to `buildRoots` in .scala-steward.conf, see #211
