### ISSUE TITLE
Laguna compilation fails with ASH versions greater than 0.4.3

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/akka-serialization-helper#217]
`sbt compile` of Laguna repo fails for all ASH versions since 0.4.4 - example logs:
```
[error] Exception thrown, message: null
[error] one error found
[error] (edgeAsset / Compile / compileIncremental) Compilation failed
[error] Total time: 82 s (01:22), completed Aug 1, 2022, 5:22:48 PM
```

We should debug the cause of failure.
- If the cause is a bug in Akka Serialization Helper - this bug should be fixed in this issue
- If the cause is not a bug in Akka Serialization Helper - help Laguna team recognize what is wrong and fix that + add some advice for users in either README or GUIDE if needed

**Comment by LukaszKontowski** [comment]
Disabling codec registration checker compiler plugin:
`Compile / scalacOptions += "-P:codec-registration-checker-plugin:--disable"`
makes compilation successful again.
Probably - some changes from https://github.com/VirtusLab/akka-serialization-helper/pull/131/files connected with Laguna code causes compilation failure

**Comment by PawelLipski** [comment]
> Disabling codec registration checker compiler plugin:

Huh the ability to turn off individual compiler plugins turns out invaluable in hindsight 😅
