### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#26]
- [x] CI + License + Maven badge (shields.io, see https://github.com/VirtusLab/git-machete-intellij-plugin/ for a sample)
- [x] Logo (#25)
- [x] Build setup (compiler plugin + dependency)
- [x] Rationale: why Jackson sucks for Akka and how it's done better here
- [x] Remember about explicit mentions of Borer! so that it doesn't create an impression that we attribute to ourselves what's actually done by Borer
- [x] Document sbt settings for dump event schema plugin/options for compiler plugin (maybe not in README but in a separate file? TBD)
- [x] Document Circe serializer with some Scala snippets

**Comment by MarconZet** [comment]
3, 4 and 5 done by #39
