### ISSUE TITLE
Support for native serializable types and/or exclusions

### ISSUE THREAD

**Issue by gervaisb** [VirtusLab/akka-serialization-helper#268]
We do have some messages (especially replies) that use `Either[XyError, XySuccess]`. However, the plugin reports an error on that type while both the left and right sides are annotated:

> [error] /acme/src/main/scala/org/acme/projections/MyProjectionHandler.scala:101:73: Either[org.acme.XyError,org.acme.XySuccess] is used as Akka message but does not extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait.
[error] Passing an object of a class that does NOT extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait as a message
[error] may cause Akka to fall back to Java serialization during runtime.
[error]
[error]         GetXy(_)
[error] &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^
[error] Make sure this type is itself annotated, or extends a type annotated with  @org.virtuslab.ash.annotation.SerializabilityTrait.

---
We also have some generated messages (from ScalaPB) that have a common supertype. However, while they are generated, we cannot annotate anything and the plugin report an error.
```
final case class MyMessage(..) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[MyMessage]
```

---

It would be great if the plugin could be configured to accept some specific types that are not annotated.

**Comment by PawelLipski** [comment]
Hmmm I'm not sure if these are truly false positives... do `Either[_,_]` and subclasses of `scalapb.GeneratedMessage` actually serialize successfully with Akka? 🤔 [SerializationTestKit](https://doc.akka.io/japi/akka/current/akka/actor/testkit/typed/scaladsl/SerializationTestKit.html) can be used to be make sure.

Btw out of curiosity, how did you learn of our plugin? ;)

**Comment by gervaisb** [comment]
At least we do not have any errors at this time..
I was not aware of the `SerializationTestKit`, that's very good to know. I'm going to use it and update that issue accordingly.

I learnt about the plugin from Twitter: https://twitter.com/VirtusLab/status/1570312428218466306

**Comment by gervaisb** [comment]
Hi there. Back with my "issue".

I do have this test that pass for a message with an `Either`.
```
val probe = testKit.createTestProbe[Either[SampleError, SampleEvent]]()
val replyTo: ActorRef[Either[SampleError, SampleEvent]] = probe.ref

val subject = MessageWithEither(
    "Hello", replyTo
)
new SerializationTestKit(system)
    .verifySerialization(subject)
```

The system is configured with:
```
akka {
  actor {
    serializers {
      // ...
      jackson-cbor = "akka.serialization.jackson.JacksonCborSerializer"
    }
    serialization-bindings {
      // ...
      "scala.util.Either" = jackson-cbor
    }
  }
}
```

However, ASH report an error:
> Either[org.acme.SampleError, org.acme.SampleEvent] is used as Akka message but does not extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait.
> [error] Passing an object of a class that does NOT extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait as a message
> [error] may cause Akka to fall back to Java serialization during runtime.
> [error]
> [error]       replyTo: ActorRef[Either[SampleError, SampleEvent]]


You are right, `Either[_,_]` is not "natively serializable" with Akka. However, if I'm not mistaken, it should be in this case.

**Comment by PawelLipski** [comment]
Wow good to know 😯 Indeed, there should be a mechanism for marking certain types defined outside the user codebase as safe for serialization. There's a [predefined list](https://github.com/VirtusLab/akka-serialization-helper/blob/main/serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala#L26)... but that's not configurable, alas ☹️

**Comment by gervaisb** [comment]
Okay, thanks. 

We use `Either` on commands only. But we do have some snapshots that are not serializable. Is there any way to "exclude" our commands from your plugin, but keep all classes related to the states?

**Comment by PawelLipski** [comment]
>  Is there any way to "exclude" our commands from your plugin, but keep all classes related to the states?

Unfortunately, there's currently some configurability (https://github.com/VirtusLab/akka-serialization-helper/blob/main/docs/GUIDE.md#serializability-checker-compiler-plugin)... but that probably doesn't cover your case in any useful manner.

Just out of curiosity... would you be interested in providing a contribution to this repo? Ofc with review & all needed support on our side. We'll eventually be able to implement it ourselves as well (esp. given that there's an external interest in the project)... but it might take a longer while (as we're busy in unrelated projects that don't even use ASH) :///

**Comment by PawelLipski** [comment]
@gervaisb actually... work in progress ;) #304

**Comment by gervaisb** [comment]
> Just out of curiosity... would you be interested in providing a contribution to this repo? 

I'd love to. Unfortunately, I do not see much time on the coming months.

Thanks for the effort in #304 ! Awesome.

**Comment by gervaisb** [comment]
Awesome ! Thanks a lot. 

Will try that ASAP.

**Comment by PawelLipski** [comment]
> Hello again. I just tested the last snapshot, and it seems to do the Job.

Gr8! 🎉  I'm running a release of v0.7.0 right now, once the packages make their way to Maven Central (which can take up to 12 hrs), you can replace the snapshot version with 0.7.0.

> However, we do have errors for generic types

Hmm this error is probably expected, as there's no guarantee that `E` will serialize in runtime indeed... would it make sense to provide a lower bound for these types, like `abstract class Projection[Event <: MySerializable]`?

Otherwise, you can take a look at `--disable-detection-generics` compiler plugin option (https://github.com/VirtusLab/akka-serialization-helper/blob/main/docs/GUIDE.md#serializability-checker-compiler-plugin)

**Comment by gervaisb** [comment]
Just upgraded to `0.7.0` everything is okay with the new parameter.
