### ISSUE TITLE
Research the options for event migration

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#28]
Pls research https://github.com/scalapenos/stamina.

1. **Does this library automatically detect accidental changes to the events, introduced by the programmer?** That's what I'm most afraid of in Hydra TBH (or any event-based software, for that matter)
2. It seems that Stamina runs on the top of spray-json... can this be replaced by Borer or Kryo (#27)?
3. Provide some short example of event migration in code... does the API feel mature enough? did you need to hack anything/check the source code of library to fix unexpected problems?
4. Are there any alternatives that claim to do the same thing out there on GitHub?

**Comment by PawelLipski** [comment]
(https://sirthias.github.io/borer/borer-core/transcoding.html to be considered for Borer)

**Comment by MarconZet** [comment]
I think this task has already been completed and could be linked with #46

**Comment by PawelLipski** [comment]
Actually... unlinked from #46. I'd say the output for this task should be the examples of migration that you've prepared for Borer/Circe... pls add them under `examples/` or sth like that
