### ISSUE TITLE
Compare the performance of Java serialization vs Jackson CBOR vs Borer vs Kryo

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#30]
Each of Jackson/Borer/Kryo claims to be faster than Java serialization... let's do a simple check (a few million calls of `SerializationTestKit#verify`?) how do they actually compare. Let's consider a few different class objects, with ADTs/Seqs/Maps involved.

**Comment by MarconZet** [comment]
Maybe @HubertBalcerzak should do it? Regardless of what I do, this task will remain relevant.

**Comment by PawelLipski** [comment]
Makes sense, let's discuss on a call today...

**Comment by PawelLipski** [comment]
To check: https://github.com/maxbundscherer/akka-serialization-comparison

**Comment by plokhotnyuk** [comment]
[Here](https://plokhotnyuk.github.io/jsoniter-scala/) is a comprehensive comparison of different JSON parsers for Scala on different JVMs using different data types and real-world samples ([sources](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark)).

Also the following PR has sources and results of comparison some JSON parsers for Scala with binary parsers for Scala /Java including Java serialization: https://github.com/dkomanov/scala-serialization/pull/8

**Comment by PawelLipski** [comment]
Thanks @plokhotnyuk ! let us take a look...

**Comment by MarconZet** [comment]
@plokhotnyuk is it possible to create a link to [plokhotnyuk.github.io/jsoniter-scala/](plokhotnyuk.github.io/jsoniter-scala/) in a way, to only show specific subset of data?

**Comment by plokhotnyuk** [comment]
@MarconZet As an option you can save it locally and remove unwonted data from `provided.js`.

A better option would be just running only required benchmarks on your env. and then using [JMH Visualizer site](jmh.morethan.io/) to plot charts or compare results.
