### ISSUE TITLE
Pekko support

### ISSUE THREAD

**Issue by MrMaxxan** [VirtusLab/akka-serialization-helper#325]
Is there any plan for Pekko support now when it has been released?

**Comment by PawelLipski** [comment]
Ha! good idea... I'll take a look how many changes would be required to adapt ASH to Pekko 🤔

**Comment by PawelLipski** [comment]
See https://github.com/VirtusLab/pekko-serialization-helper/releases/tag/v0.7.3... it should soon be published to Maven Central as well 📦
