### ISSUE TITLE
Is it possible to check only if Event and State is serializable?

### ISSUE THREAD

**Issue by IlyaHalsky** [VirtusLab/akka-serialization-helper#381]
Hi, 

I'm working on project with akka persistence but without akka cluster. In this case I don't need to ensure that Command is serializable. Is it possible to configure plugin to check only for Event and State?

**Comment by IlyaHalsky** [comment]
Here is simplified version, just plain EventSourcedBehavior.
```scala
case class Command(test: String)

case class OffsetEvent(topic: String, offset: Long) extends ProcessingSerializable

case class State(offsets: Map[String, Long]) extends ProcessingSerializable

object PersistentKafkaConsumer {

  def apply(id: String): Behavior[Command] =
    Behaviors.setup { context =>
      EventSourcedBehavior[Command, OffsetEvent, State](
        persistenceId = PersistenceId.ofUniqueId(id),
        emptyState = State(Map.empty),
        commandHandler = (state, command) => Effect.none,
        eventHandler = (state, event) => state
      )
    }
}
```

**Comment by PawelLipski** [comment]
> Plugin specifically highlights val test = context.spawn(PersistentKafkaConsumer("test-consumer"), "PersistentKafkaConsumer-test")

Okay... if you could share the entire error message, it's still gonna be helpful 🤔 

I can implement the feature to filter the specific `org.virtuslab.ash.ClassType`s (`Message`, `PersistentEvent`, `PersistentState`)... albeit due to my workload in a commercial project, I'd only be able to start around Dec 20th. If you'd need the feature available earlier, I can provide you with guidelines on how to implement. It should be relatively easy as all the internal machinery to discern the types is already there, it's just a matter of wiring it up to compiler plugin flags/sbt keys.

**Comment by PawelLipski** [comment]
Okay, I've finally got some free throughput to do this 😅 @IlyaHalsky before I start, could you share the full error message from compilation?

**Comment by IlyaHalsky** [comment]
Sorry for not replying, was under the weather for past week.
Plugin spits out quite a lot of errors:
```
C:\Users\ilyak\Desktop\Cone\akka-persistence\src\main\scala\PersistentConsumer.scala:16:26
Command is used as Akka message but does not extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait.
Passing an object of a class that does NOT extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait as a message
may cause Akka to fall back to Java serialization during runtime.


  def apply(id: String): Behavior[Command] =

C:\Users\ilyak\Desktop\Cone\akka-persistence\src\main\scala\PersistentConsumer.scala:8:12
Make sure this type is itself annotated, or extends a type annotated with  @org.virtuslab.ash.annotation.SerializabilityTrait.
case class Command(test: String)

C:\Users\ilyak\Desktop\Cone\akka-persistence\src\main\scala\ProcessingApp.scala:8:11
Command is used as Akka message but does not extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait.
Passing an object of a class that does NOT extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait as a message
may cause Akka to fall back to Java serialization during runtime.


      val test = context.spawn(PersistentKafkaConsumer("test-consumer"), "PersistentKafkaConsumer-test")
```

**Comment by IlyaHalsky** [comment]
Also wanted to note, if you use in a project `ThisBuild / scalaVersion := "2.13.12"` compilation fails with 
```
scala: ## Exception when compiling 4 sources to C:\Users\ilyak\Desktop\Cone\akka-persistence\target\scala-2.13\classes
java.lang.NoSuchMethodError: 'void scala.tools.nsc.reporters.Reporter.error(scala.reflect.internal.util.Position, java.lang.String)'
org.virtuslab.ash.SerializabilityCheckerCompilerPluginComponent$$anon$1.$anonfun$apply$7(SerializabilityCheckerCompilerPluginComponent.scala:173)
scala.collection.IterableOnceOps.$anonfun$foldRight$1(IterableOnce.scala:695)
scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
scala.collection.immutable.List.foldLeft(List.scala:79)
scala.collection.IterableOnceOps.foldRight(IterableOnce.scala:695)
scala.collection.IterableOnceOps.foldRight$(IterableOnce.scala:695)
scala.collection.AbstractIterable.foldRight(Iterable.scala:933)
org.virtuslab.ash.SerializabilityCheckerCompilerPluginComponent$$anon$1.apply(SerializabilityCheckerCompilerPluginComponent.scala:147)
scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:480)```

**Comment by PawelLipski** [comment]
Okay! I've added compiler plugins flags... pls check [GUIDE.md](https://github.com/VirtusLab/akka-serialization-helper/blob/main/docs/GUIDE.md#serializability-checker-compiler-plugin) for `--exclude-persistent-events` and `--exclude-persistent-states`

**Comment by PawelLipski** [comment]
Oh, you'd need to wait for v0.8.0 to be available... this will probably happen in a few hours from now (you can check [Maven Central](https://repo1.maven.org/maven2/org/virtuslab/ash/annotation_2.13/) directly)

**Comment by IlyaHalsky** [comment]
Thank you so much, constantly refreshing maven 🙇‍♂️
