### ISSUE TITLE
Consider merging serializability-checker compiler plugin into sbt plugin

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#42]
Rationale: It'd be easiest for the users if they can just add a single sbt plugin and everything they need comes out of the box (even if they aren't fully aware of what they really need yet!)

**Comment by MarconZet** [comment]
I think that's a great idea 👍 
Adding to project one sbt plugin `sbt-ash` and enabling/disabling features in an easy to understand way.
