### ISSUE TITLE
Research compatibility of the format of serialized events between the versions of the given serialization library

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#43]
https://github.com/altoo-ag/akka-kryo-serialization#features -> for Kryo, the approach is reasonable/semantic - compatibility of binary format is only guaranteed b/w patch/minor updates, but not major updates.

The end result of this task should be another row in the table in README.md, with a comparison of the **documented** approach to compatibility b/w libraries.

If any library does NOT mention anything about its compatibility guarantees, we should NOT check it experimentally. In fact, it's a warning sign &mdash; if they don't _document_ such guarantees, do they even _care_ about them in the first place?

**Comment by MarconZet** [comment]
It seems Circe is not afraid of breaking stuff when it comes to binary compatibility (https://github.com/circe/circe/issues/1754), but there is nothing on format compatibility.

**Comment by MarconZet** [comment]
Truth be told, this kind of information is hard to find. I browsed through documentation of all serialisers listed in README.md and didn't find any explicit information regarding our concern.

**Comment by PawelLipski** [comment]
Whooops not good 😅 ok so only akka-kryo stated **anything** in this respect?

**Comment by MarconZet** [comment]
Exactly, we can only bet which serializers are less likely to change the format in the long run. Automatic testing is a must in this aspect.
