### ISSUE TITLE
Add docs specifying the problems with Jackson serialization, esp. around ADTs

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#45]

**Comment by MarconZet** [comment]
From README.md:
* ADTs requires amount of annotation equal to or exceeding the actual type definitions
* poor support for case object - needs sealed trait per case object and a custom deserializer

**Comment by MarconZet** [comment]
I don't think more is required

**Comment by PawelLipski** [comment]
Okay, maybe also mention that new instances of Scala `object`s are getting created, thus causing `object`s to no longer be actual singletons

**Comment by PawelLipski** [comment]
(and pattern matching breaking b/c of that)

**Comment by MarconZet** [comment]
Ok added in #46

**Comment by MarconZet** [comment]
Maybe we should create a new subproject called example, where we could put all our loose thoughts?

**Comment by PawelLipski** [comment]
Okay, makes sense... that would also be a good place for examples on how to do the migration of events in Borer vs Circe

**Comment by MarconZet** [comment]
Ok, then I will unlink the issue and create PR with example directory

**Comment by MarconZet** [comment]
This is covered by Akka documentation [here](https://doc.akka.io/docs/akka/current/serialization-jackson.html#annotations)

**Comment by MarconZet** [comment]
The more I look at this issue and #69, the less sense I see in them. This stuff is already covered by Akka documentation. 
The only thing that's missing, is what happens if you forget to put the required boilerplate.

**Comment by PawelLipski** [comment]
Okay! makes sense, let's then just include an abridged version into the sphere.it slides
