### ISSUE TITLE
`dumpEventSchemaOutputFilename` does NOT allow for specifying absolute path

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#53]
The output file is always assumed to live under `<subproject-directory>/target` :/

E.g. when I passed full path (`/home/plipski/hydra-backend/target/events-current.json`) to the file, I've got:

```
(hydra-backend / dumpEventSchema) java.nio.file.NoSuchFileException: /home/plipski/hydra-backend/services/target/home/plipski/hydra-backend/target/events-current.json
```

:/

**Comment by MarconZet** [comment]
Could you provide what key did you change?

**Comment by PawelLipski** [comment]
Hmm I've tried sth like:

```scala
sbt -batch ';set Global / dumpEventSchema / dumpEventSchemaOutputFilename := "'$output'"; dumpEventSchema'
```

in my Bash script

**Comment by MarconZet** [comment]
This is the source of the problem.
From `DumpEventSchemaKeys.scala`:
```scala
lazy val dumpEventSchemaOutputFile = taskKey[File]("Output file to dump event schema to")
lazy val dumpEventSchemaOutputFilename = settingKey[String]("Filename to dump event schema to")
```
As you can see, File != Filename.

**Comment by PawelLipski** [comment]
`dumpEventSchemaOutputFile` isn't easily settable anyway right?

```
sbt:phoenix> set Global / dumpEventSchema / dumpEventSchemaOutputFile := "/home/plipski/hydra-backend/target/foo.json"
<set>:1: error: type mismatch;
 found   : String("/home/plipski/hydra-backend/target/foo.json")
 required: sbt.File
    (which expands to)  java.io.File
Global / dumpEventSchema / dumpEventSchemaOutputFile := "/home/plipski/hydra-backend/target/foo.json"
```

Maybe there should be sth like `dumpEventSchemaOutputDirectoryPath` of type `String` instead, containing an absolute path to the output directory?

**Comment by MarconZet** [comment]
>  `dumpEventSchemaOutputFile` isn't easily settable anyway right?
You are right, I will create new setting, and notify you, when it's done
