### ISSUE TITLE
Research security of deserializers from the PoV of deserialization gadgets

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#69]
I thought it's only a problem of Java serialization until I've seen:

https://github.com/akka/akka/blob/master/akka-serialization-jackson/src/main/resources/reference.conf#L239

So at least that's also a potential problem of Jackson, which suggests other serializers might potentially be affected.

**Expected output of this task**: consider adding a new row in README.md table that compares the serializers from that PoV.

**Comment by MarconZet** [comment]
Jackson uses reflection and can deserialize data into any class the data tells it to. Circe can only deserialize into classes we provide codecs for, and the class is chosen based on provided manifest.

**Comment by PawelLipski** [comment]
Ok, I think adding a mention to the README would still be useful

**Comment by MarconZet** [comment]
This is covered by Akka documentaion [here](https://doc.akka.io/docs/akka/current/serialization-jackson.html#security)

**Comment by PawelLipski** [comment]
Okay, again just a mention in conference preso should be enough
