### ISSUE TITLE
Serializability checker doesn't whitelist types serialized by Akka internal Serializers

### ISSUE THREAD

**Issue by MarconZet** [VirtusLab/akka-serialization-helper#71]
The easiest reproduce:

```scala
val a: ActorRef[Int] = ???
```

**Comment by PawelLipski** [comment]
@MarconZet you mean, the above part itself isn't a complete repro, is it? You need to **`!`-send** a message of type `ActorRef[...]` to trigger a false-positive error, right??

**Comment by MarconZet** [comment]
I looked for default serializers provided by Akka in Hydra and created a list of types. Types that would case this false-positive are:
```
com.google.protobuf.GeneratedMessage
com.google.protobuf.GeneratedMessageV3
com.typesafe.config.Config
com.typesafe.config.impl.SimpleConfig
```

I would add 2 new entries to whitelist:
```
com.google.protobuf.*
com.typesafe.config.*
```

**Comment by MarconZet** [comment]
Actually the problem is broader then expected, this is the full list of false-positives:
```com.google.protobuf.GeneratedMessage
com.google.protobuf.GeneratedMessageV3
com.typesafe.config.Config
com.typesafe.config.impl.SimpleConfig
java.io.Serializable
java.lang.Boolean
java.lang.Integer
java.lang.Long
java.lang.String
java.lang.Throwable
java.util.Optional
java.util.concurrent.TimeoutException
phoenix.CborSerializable
scala.Boolean
scala.Int
scala.Long
scala.None$
scala.Some
```

**Comment by PawelLipski** [comment]
Hmm wrt. `java.io.Serializable`... if you try `!`-sending a message of type implementing this interface (but not any user-defined marker interface like `CborSerializable`)... what would Akka do then? would it serialize the message using Java serialization? that sounds like we shouldn't whitelist `java.io.Serializable`

**Comment by PawelLipski** [comment]
Also! could you leave some hints to the _future generations_ on what you specifically did to extract the list above?

**Comment by MarconZet** [comment]
I printed out during runtime `config.getConfig("akka.actor.serialization-bindings")`.
